/*
  File completely generated by Claude.ai with prompt:
    help me with instructions of how to create a seed file
    with 10 users and different information. 
    give me 10 famous names and the actual data for them.
*/

import * as dotenv from 'dotenv';
import { DataSource } from 'typeorm';
import { User } from './users/entities/user.entity';
dotenv.config({ path: require('path').resolve(__dirname, '../../.env') });

const BASE_URL = process.env.SEED_API_URL || 'http://localhost:3000';

const users = [
  {
    name: 'Frida Kahlo',
    birthday: new Date('1907-07-06'),
    luckyNumber: 7,
    superpowers: [
      'painting reality',
      'surviving everything',
      'iconic eyebrows',
      'flower crowns',
      'self-portraiture',
    ],
    avatar: {
      bgColor: '#f2d0c0',
      svg: '<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200"><circle cx="100" cy="90" r="50" fill="#f5c5a3" stroke="#333" stroke-width="2"/><path d="M60 85 Q100 70 140 85" stroke="#333" stroke-width="3" fill="none"/><line x1="70" y1="100" x2="130" y2="100" stroke="#8B0000" stroke-width="2"/><circle cx="85" cy="95" r="5" fill="#333"/><circle cx="115" cy="95" r="5" fill="#333"/><path d="M80 130 Q100 160 120 130" stroke="#333" stroke-width="2" fill="#f5c5a3"/></svg>',
    },
  },
  {
    name: 'Albert Einstein',
    birthday: new Date('1879-03-14'),
    luckyNumber: 3,
    superpowers: [
      'bending spacetime',
      'thought experiments',
      'wild hair',
      'playing violin',
      'forgetting socks',
    ],
    avatar: {
      bgColor: '#d6eaf8',
      svg: '<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200"><circle cx="100" cy="100" r="55" fill="#f0e0c0" stroke="#333" stroke-width="2"/><path d="M55 70 Q60 40 80 50 Q70 30 100 35 Q130 30 120 50 Q140 40 145 70" stroke="#ccc" stroke-width="4" fill="#e8e8e8"/><circle cx="85" cy="95" r="6" fill="#333"/><circle cx="115" cy="95" r="6" fill="#333"/><path d="M75 90 Q85 85 95 90" stroke="#333" stroke-width="2" fill="none"/><path d="M105 90 Q115 85 125 90" stroke="#333" stroke-width="2" fill="none"/><path d="M85 120 Q100 130 115 120" stroke="#333" stroke-width="2" fill="none"/></svg>',
    },
  },
  {
    name: 'Beyoncé',
    birthday: new Date('1981-09-04'),
    luckyNumber: 4,
    superpowers: [
      'flawless performance',
      'running the world',
      'surprise albums',
      'formation',
      'breaking the internet',
    ],
    avatar: {
      bgColor: '#fef9e7',
      svg: '<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200"><circle cx="100" cy="95" r="50" fill="#c8944a" stroke="#333" stroke-width="2"/><path d="M55 75 Q100 30 145 75 Q145 55 100 50 Q55 55 55 75" fill="#FFD700" stroke="#b8860b" stroke-width="1"/><circle cx="87" cy="92" r="6" fill="#333"/><circle cx="113" cy="92" r="6" fill="#333"/><circle cx="89" cy="90" r="2" fill="#fff"/><circle cx="115" cy="90" r="2" fill="#fff"/><path d="M88 108 Q100 118 112 108" stroke="#333" stroke-width="2" fill="none"/></svg>',
    },
  },
  {
    name: 'Leonardo da Vinci',
    birthday: new Date('1452-04-15'),
    luckyNumber: 15,
    superpowers: [
      'inventing the future',
      'painting smiles',
      'ambidextrous genius',
      'mirror writing',
      'designing flying machines',
    ],
    avatar: {
      bgColor: '#fdf2e9',
      svg: '<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200"><circle cx="100" cy="95" r="50" fill="#e8c99a" stroke="#333" stroke-width="2"/><path d="M55 80 Q100 40 145 80 Q140 50 100 45 Q60 50 55 80" fill="#d4a96a" stroke="#8B6914" stroke-width="1"/><circle cx="87" cy="93" r="5" fill="#6b4c2a"/><circle cx="113" cy="93" r="5" fill="#6b4c2a"/><path d="M75 85 Q85 80 95 85" stroke="#8B6914" stroke-width="2" fill="none"/><path d="M105 85 Q115 80 125 85" stroke="#8B6914" stroke-width="2" fill="none"/><path d="M85 115 Q100 122 115 115" stroke="#8B6914" stroke-width="2" fill="none"/></svg>',
    },
  },
  {
    name: 'Marie Curie',
    birthday: new Date('1867-11-07'),
    luckyNumber: 2,
    superpowers: [
      'radioactivity',
      'breaking barriers',
      'double Nobel prize',
      'isolating polonium',
      'glowing in the dark',
    ],
    avatar: {
      bgColor: '#e8f8f5',
      svg: '<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200"><circle cx="100" cy="95" r="50" fill="#f0e8d8" stroke="#333" stroke-width="2"/><path d="M60 75 Q100 50 140 75 Q135 55 100 52 Q65 55 60 75" fill="#8B7355" stroke="#6b5535" stroke-width="1"/><circle cx="88" cy="92" r="6" fill="#4a3728"/><circle cx="112" cy="92" r="6" fill="#4a3728"/><path d="M86 112 Q100 120 114 112" stroke="#6b5535" stroke-width="2" fill="none"/><circle cx="100" cy="160" r="15" fill="none" stroke="#7EC8A4" stroke-width="2" stroke-dasharray="4,2"/></svg>',
    },
  },
  {
    name: 'Ada Lovelace',
    birthday: new Date('1815-12-10'),
    luckyNumber: 1,
    superpowers: [
      'writing the first algorithm',
      'seeing the future of computers',
      'poetic science',
      "being Lord Byron's daughter",
      'debugging before computers existed',
    ],
    avatar: {
      bgColor: '#f5eef8',
      svg: '<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200"><circle cx="100" cy="95" r="50" fill="#f5e6d3" stroke="#333" stroke-width="2"/><path d="M58 80 Q100 45 142 80 Q138 52 100 48 Q62 52 58 80" fill="#4a3020" stroke="#3a2010" stroke-width="1"/><circle cx="88" cy="93" r="5" fill="#5c3d2e"/><circle cx="112" cy="93" r="5" fill="#5c3d2e"/><path d="M87 113 Q100 121 113 113" stroke="#8B5c4a" stroke-width="2" fill="none"/><text x="72" y="178" font-size="10" fill="#9B59B6" font-family="monospace">01001010</text></svg>',
    },
  },
  {
    name: 'Nikola Tesla',
    birthday: new Date('1856-07-10'),
    luckyNumber: 3,
    superpowers: [
      'controlling electricity',
      'photographic memory',
      'sleeping 2 hours a night',
      'talking to pigeons',
      'inventing AC current',
    ],
    avatar: {
      bgColor: '#eaf4fc',
      svg: '<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200"><circle cx="100" cy="95" r="50" fill="#e8e0d0" stroke="#333" stroke-width="2"/><path d="M62 78 Q100 50 138 78 Q134 54 100 50 Q66 54 62 78" fill="#2c2c2c" stroke="#1a1a1a" stroke-width="1"/><circle cx="87" cy="93" r="6" fill="#2c3e50"/><circle cx="113" cy="93" r="6" fill="#2c3e50"/><path d="M86 113 Q100 120 114 113" stroke="#555" stroke-width="2" fill="none"/><path d="M155 50 L165 65 L158 65 L168 80" stroke="#3498DB" stroke-width="2" fill="none"/><path d="M168 50 L158 65 L165 65 L155 80" stroke="#3498DB" stroke-width="2" fill="none"/></svg>',
    },
  },
  {
    name: 'Cleopatra',
    birthday: new Date('0069-01-01'),
    luckyNumber: 7,
    superpowers: [
      'speaking 9 languages',
      'political mastery',
      'legendary charisma',
      'ruling Egypt solo',
      'outsmarting Julius Caesar',
    ],
    avatar: {
      bgColor: '#fef5e4',
      svg: '<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200"><circle cx="100" cy="95" r="50" fill="#d4a96a" stroke="#333" stroke-width="2"/><path d="M55 80 L100 50 L145 80 L140 70 L100 42 L60 70 Z" fill="#C0A020" stroke="#8B7015" stroke-width="1"/><line x1="72" y1="92" x2="60" y2="95" stroke="#1a1a1a" stroke-width="2"/><line x1="128" y1="92" x2="140" y2="95" stroke="#1a1a1a" stroke-width="2"/><circle cx="87" cy="95" r="6" fill="#1a1a1a"/><circle cx="113" cy="95" r="6" fill="#1a1a1a"/><path d="M87 115 Q100 124 113 115" stroke="#C0A020" stroke-width="2" fill="none"/></svg>',
    },
  },
  {
    name: 'David Bowie',
    birthday: new Date('1947-01-08'),
    luckyNumber: 8,
    superpowers: [
      'shapeshifting',
      'inventing genres',
      'heterochromia',
      'glam rock',
      'living on mars',
    ],
    avatar: {
      bgColor: '#fdedec',
      svg: '<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200"><circle cx="100" cy="95" r="50" fill="#f0d8c0" stroke="#333" stroke-width="2"/><path d="M55 72 Q100 25 145 72 Q150 45 130 38 Q100 28 70 38 Q50 45 55 72" fill="#e8c8a0" stroke="#c8a880" stroke-width="1"/><circle cx="87" cy="94" r="6" fill="#1a6b1a"/><circle cx="113" cy="94" r="6" fill="#8B4513"/><circle cx="89" cy="92" r="2" fill="#fff"/><circle cx="115" cy="92" r="2" fill="#fff"/><path d="M87 113 Q100 122 113 113" stroke="#c08060" stroke-width="2" fill="none"/></svg>',
    },
  },
  {
    name: 'Rosalind Franklin',
    birthday: new Date('1920-07-25'),
    luckyNumber: 51,
    superpowers: [
      'X-ray vision',
      'decoding DNA',
      'proving everyone wrong',
      'photo 51',
      'coal microstructure analysis',
    ],
    avatar: {
      bgColor: '#e8f8f5',
      svg: '<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200"><circle cx="100" cy="95" r="50" fill="#f0e8e0" stroke="#333" stroke-width="2"/><path d="M62 78 Q100 48 138 78 Q134 55 100 51 Q66 55 62 78" fill="#3d2b1f" stroke="#2a1a0f" stroke-width="1"/><circle cx="88" cy="94" r="6" fill="#3d2b1f"/><circle cx="112" cy="94" r="6" fill="#3d2b1f"/><path d="M87 113 Q100 121 113 113" stroke="#8B6050" stroke-width="2" fill="none"/><path d="M155 140 Q160 125 155 110 Q150 125 155 140" stroke="#1ABC9C" stroke-width="1.5" fill="none"/><path d="M165 140 Q160 125 165 110 Q170 125 165 140" stroke="#1ABC9C" stroke-width="1.5" fill="none"/><line x1="155" y1="120" x2="165" y2="125" stroke="#1ABC9C" stroke-width="1"/><line x1="155" y1="130" x2="165" y2="135" stroke="#1ABC9C" stroke-width="1"/></svg>',
    },
  },
];

async function clearUsers() {
  const dataSource = new DataSource({
    type: 'postgres',
    host: process.env.DB_HOST,
    port: Number(process.env.DB_PORT),
    username: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME,
    entities: [User],
  });

  await dataSource.initialize();
  await dataSource.getRepository(User).clear();
  await dataSource.destroy();
  console.log('🗑️  Cleared users table');
}

async function seed() {
  if (process.argv.includes('--fresh')) {
    await clearUsers();
  }

  for (const user of users) {
    const res = await fetch(`${BASE_URL}/users`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(user),
    });

    if (!res.ok) {
      const error = await res.text();
      throw new Error(`Failed to seed ${user.name}: ${error}`);
    }

    console.log(`✅ Seeded ${user.name}`);
  }
}

seed().catch((e) => {
  console.error(e);
  process.exit(1);
});
